# Revenue Column

In [2]:
import pandas as pd

df_clean = pd.read_csv("cleaned_online_retail.csv")

In [3]:
# Reveue = Quantity X Price
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['Price']

In [4]:
df_clean[['Quantity','Price','Revenue']].head()
# Created a Revenue feature by multiplying Quantity with UnitPrice to represent total transaction value.

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

# Extract Order Month

In [5]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

In [6]:
df_clean['OrderMonth'] = df_clean['InvoiceDate'].dt.month

In [7]:
df_clean[['InvoiceDate','OrderMonth']].head()
# Extracted OrderMonth from InvoiceDate to analyze monthly sales trends.

          InvoiceDate  OrderMonth
0 2009-12-01 07:45:00          12
1 2009-12-01 07:45:00          12
2 2009-12-01 07:45:00          12
3 2009-12-01 07:45:00          12
4 2009-12-01 07:45:00          12

# Extract Order Year

In [8]:
df_clean['OrderYear'] = df_clean['InvoiceDate'].dt.year

In [11]:
df_clean[['InvoiceDate','OrderYear']].head(20)
# Extracted OrderYear to enable yearly sales comparisons.

           InvoiceDate  OrderYear
0  2009-12-01 07:45:00       2009
1  2009-12-01 07:45:00       2009
2  2009-12-01 07:45:00       2009
3  2009-12-01 07:45:00       2009
4  2009-12-01 07:45:00       2009
5  2009-12-01 07:45:00       2009
6  2009-12-01 07:45:00       2009
7  2009-12-01 07:45:00       2009
8  2009-12-01 07:46:00       2009
9  2009-12-01 07:46:00       2009
10 2009-12-01 07:46:00       2009
11 2009-12-01 07:46:00       2009
12 2009-12-01 09:06:00       2009
13 2009-12-01 09:06:00       2009
14 2009-12-01 09:06:00       2009
15 2009-12-01 09:06:00       2009
16 2009-12-01 09:06:00       2009
17 2009-12-01 09:06:00       2009
18 2009-12-01 09:06:00       2009
19 2009-12-01 09:06:00       2009

# Creating Customer Tenure

In [12]:
# Customer Tenure : How long a customer has been active since their first purchase.

In [13]:
# SQL fromula
#Tenure = Current Order Date - Customer First Purchase Date

In [17]:
# first purchase per customer
first_purchase = df_clean.groupby('Customer ID')['InvoiceDate'].min()

In [19]:
# first purchase to dataset
df_clean['FirstPurchaseDate'] = df_clean['Customer ID'].map(first_purchase)

In [20]:
# Calculate tenure
df_clean['CustomerTenureDays'] = (df_clean['InvoiceDate'] - df_clean['FirstPurchaseDate']).dt.days

In [21]:
df_clean[['Customer ID','InvoiceDate','FirstPurchaseDate','CustomerTenureDays']].head()

   Customer ID         InvoiceDate   FirstPurchaseDate  CustomerTenureDays
0      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00                   0
1      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00                   0
2      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00                   0
3      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00                   0
4      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00                   0

In [24]:
# tenure is calculated as the difference between the transaction date and the customer's first purchase date, 
# this helps analyze customer loyalty and behaviour

In [25]:
df_clean.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,OrderMonth,OrderYear,FirstPurchaseDate,CustomerTenureDays
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,12,2009,2009-12-01 07:45:00,0
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,12,2009,2009-12-01 07:45:00,0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,12,2009,2009-12-01 07:45:00,0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,12,2009,2009-12-01 07:45:00,0
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,12,2009,2009-12-01 07:45:00,0

In [26]:
df_clean.to_csv("online_retail_enriched.csv", index=False)

In [27]:
'''
Feature engineering was performed to enhance the dataset with meaningful variables. 
Revenue was calculated from Quantity and UnitPrice. 
Temporal features such as OrderMonth and OrderYear were extracted from InvoiceDateto support time-based analysis.
Additionally, customer tenure was computed to measure customer longevity and support customer behavior analysis.
'''

'\nFeature engineering was performed to enhance the dataset with meaningful variables. \nRevenue was calculated from Quantity and UnitPrice. \nTemporal features such as OrderMonth and OrderYear were extracted from InvoiceDateto support time-based analysis.\nAdditionally, customer tenure was computed to measure customer longevity and support customer behavior analysis.\n'